name: grade_book_tania
description: "Aplicacion para gestionar estudiantes y notas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  supabase_flutter: ^2.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#1565C0"
  image: assets/splash2.png
  android_12:
    color: "#1565C0"
    image: assets/splash2.png
